language: python

python:
  - 2.7
  - 3.4

env:
  - DJANGO=https://www.djangoproject.com/download/1.7c3/tarball/

install:
  - pip install $DJANGO
  - pip install coverage
  - pip install coveralls
  - python setup.py develop

before_script:
  - django-admin.py startproject project
  - cd project

script: coverage run --source='italian_utils' manage.py test italian_utils
after_success: coveralls