language: python

python:
  - 2.7
  - 3.6

env:
  - DJANGO=https://www.djangoproject.com/download/1.11/tarball/

install:
  - pip install $DJANGO
  - pip install coverage
  - pip install coveralls
  - python setup.py develop

before_script:
  - django-admin.py startproject project
  - cd project
  - mkdir -p italian_utils/tests
  - curl -o italian_utils/tests/comuni-italiani.csv https://www.istat.it/storage/codici-unita-amministrative/Elenco-comuni-italiani.csv

script: coverage run --source='italian_utils' manage.py test italian_utils
after_success: coveralls
