language: python

python:
  - 2.7
  - 3.6

env:
  matrix:
    - DJANGO_URL=https://www.djangoproject.com/download/1.11/tarball/
    - DJANGO_URL=https://www.djangoproject.com/download/2.1.7/tarball/

matrix:
  exclude:
    - python: 2.7
      env: DJANGO_URL=https://www.djangoproject.com/download/2.1.7/tarball/

install:
  - pip install $DJANGO_URL
  - pip install coverage
  - pip install coveralls
  - python setup.py develop

before_script:
  - django-admin.py startproject project
  - cd project
  - mkdir -p italian_utils/tests
  - curl -o italian_utils/tests/comuni-italiani.csv https://www.istat.it/storage/codici-unita-amministrative/Elenco-comuni-italiani.csv

script: coverage run --source='italian_utils' manage.py test italian_utils
after_success: coveralls
