language: python

python:
  - 2.7
  - 3.4

env:
  - DJANGO=django==1.6
  - DJANGO=https://www.djangoproject.com/download/1.7c3/tarball/

install:
  - pip install $DJANGO
  - python setup.py install

before_script:
  - django-admin.py startproject project
  - cd project
  - python manage.py migrate

script: python manage.py test italian_utils